# Site settings
title: Centerified
email: askesian@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Experiments and musings of a FED
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://centerified.com" # the base hostname & protocol for your site
twitter_username: askesian
github_username:  askesian
github: {
  "hostname": "centerified.com",
  "pages_hostname": "askesian.github.io",
  "api_url": "https://api.github.com",
  "environment": "dotcom",
  "owner_name": "askesian",
  "owner_url": "https://github.com/askesian",
  "repository_url": "https://github.com/askesian/centerified",
  "repository_name": "centerified",
  "is_user_page": false,
  "is_project_page": true,
  "show_downloads": true,
  "url": "http://www.centerified.com"
}

# jekyll-assets config
assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/posts
  css_compressor: sass
  js_compressor:  uglifier
  cache:          true

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - .gitignore
